import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@styles/Home.module.css';
import Layout from '@layouts/Layout';
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Devily</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>children입니다</div>
      </Layout>
    </div>
  );
};

export default Home;
